package steerlist

var Services = []Service{
	{ID: "openai", Name: "OpenAI"},
	{ID: "anthropic", Name: "Claude"},
	{ID: "gemini", Name: "Gemini"},
	{ID: "copilot", Name: "Microsoft Copilot"},
	{ID: "github-copilot", Name: "GitHub Copilot"},
	{ID: "grok", Name: "Grok"},
	{ID: "perplexity", Name: "Perplexity"},
	{ID: "deepseek", Name: "DeepSeek"},
	{ID: "mistral", Name: "Mistral"},
	{ID: "poe", Name: "Poe"},
	{ID: "huggingface", Name: "Hugging Face"},
	{ID: "groq", Name: "Groq"},
	{ID: "manus", Name: "Manus"},
	{ID: "cerebras", Name: "Cerebras"},
	{ID: "character-ai", Name: "Character.AI"},
	{ID: "midjourney", Name: "Midjourney"},
	{ID: "suno", Name: "Suno"},
	{ID: "udio", Name: "Udio"},
	{ID: "elevenlabs", Name: "ElevenLabs"},
	{ID: "runway", Name: "Runway"},
	{ID: "pika", Name: "Pika"},
	{ID: "leonardo", Name: "Leonardo"},
	{ID: "ideogram", Name: "Ideogram"},
	{ID: "deepl", Name: "DeepL"},
	{ID: "openrouter", Name: "OpenRouter"},
	{ID: "genspark", Name: "Genspark"},
	{ID: "recraft", Name: "Recraft"},
	{ID: "youtube", Name: "YouTube"},
	{ID: "twitch", Name: "Twitch"},
	{ID: "netflix", Name: "Netflix"},
	{ID: "spotify", Name: "Spotify"},
	{ID: "kick", Name: "Kick"},
	{ID: "soundcloud", Name: "SoundCloud"},
	{ID: "apple-music", Name: "Apple Music"},
	{ID: "apple-tvplus", Name: "Apple TV+"},
	{ID: "disney", Name: "Disney+"},
	{ID: "hbo", Name: "HBO Max"},
	{ID: "primevideo", Name: "Prime Video"},
	{ID: "hulu", Name: "Hulu"},
	{ID: "deezer", Name: "Deezer"},
	{ID: "tidal", Name: "Tidal"},
	{ID: "vimeo", Name: "Vimeo"},
	{ID: "dailymotion", Name: "Dailymotion"},
	{ID: "plex", Name: "Plex"},
	{ID: "bandcamp", Name: "Bandcamp"},
	{ID: "rumble", Name: "Rumble"},
	{ID: "dazn", Name: "DAZN"},
	{ID: "mubi", Name: "MUBI"},
	{ID: "crunchyroll", Name: "Crunchyroll"},
	{ID: "lastfm", Name: "Last.fm"},
	{ID: "meta", Name: "Instagram, Facebook"},
	{ID: "x", Name: "X"},
	{ID: "tiktok", Name: "TikTok"},
	{ID: "reddit", Name: "Reddit"},
	{ID: "linkedin", Name: "LinkedIn"},
	{ID: "pinterest", Name: "Pinterest"},
	{ID: "snap", Name: "Snapchat"},
	{ID: "tumblr", Name: "Tumblr"},
	{ID: "bluesky", Name: "Bluesky"},
	{ID: "quora", Name: "Quora"},
	{ID: "medium", Name: "Medium"},
	{ID: "patreon", Name: "Patreon"},
	{ID: "deviantart", Name: "DeviantArt"},
	{ID: "pixiv", Name: "pixiv"},
	{ID: "imgur", Name: "Imgur"},
	{ID: "flickr", Name: "Flickr"},
	{ID: "telegram", Name: "Telegram"},
	{ID: "discord", Name: "Discord"},
	{ID: "whatsapp", Name: "WhatsApp"},
	{ID: "signal", Name: "Signal"},
	{ID: "viber", Name: "Viber"},
	{ID: "line", Name: "LINE"},
	{ID: "teamspeak", Name: "TeamSpeak"},
	{ID: "steam", Name: "Steam"},
	{ID: "epicgames", Name: "Epic Games"},
	{ID: "activision-blizzard", Name: "Battle.net"},
	{ID: "ea", Name: "EA"},
	{ID: "riot", Name: "Riot Games"},
	{ID: "roblox", Name: "Roblox"},
	{ID: "mojang", Name: "Minecraft"},
	{ID: "xbox", Name: "Xbox"},
	{ID: "playstation", Name: "PlayStation"},
	{ID: "nintendo", Name: "Nintendo"},
	{ID: "ubisoft", Name: "Ubisoft"},
	{ID: "take-two", Name: "Rockstar Games"},
	{ID: "gog", Name: "GOG"},
	{ID: "wargaming", Name: "Wargaming"},
	{ID: "gaijin", Name: "Gaijin"},
	{ID: "escapefromtarkov", Name: "Escape from Tarkov"},
	{ID: "faceit", Name: "FACEIT"},
	{ID: "supercell", Name: "Supercell"},
	{ID: "hoyoverse", Name: "HoYoverse"},
	{ID: "pubg", Name: "PUBG"},
	{ID: "curseforge", Name: "CurseForge"},
	{ID: "modrinth", Name: "Modrinth"},
	{ID: "itchio", Name: "itch.io"},
	{ID: "humblebundle", Name: "Humble Bundle"},
	{ID: "geforce-now", Name: "GeForce NOW"},
	{ID: "chess", Name: "Chess.com"},
	{ID: "bethesda", Name: "Bethesda"},
	{ID: "notion", Name: "Notion"},
	{ID: "slack", Name: "Slack"},
	{ID: "zoom", Name: "Zoom"},
	{ID: "google-meet", Name: "Google Meet"},
	{ID: "figma", Name: "Figma"},
	{ID: "canva", Name: "Canva"},
	{ID: "miro", Name: "Miro"},
	{ID: "atlassian", Name: "Atlassian"},
	{ID: "adobe", Name: "Adobe"},
	{ID: "grammarly", Name: "Grammarly"},
	{ID: "dropbox", Name: "Dropbox"},
	{ID: "mega", Name: "MEGA"},
	{ID: "evernote", Name: "Evernote"},
	{ID: "wix", Name: "Wix"},
	{ID: "coursera", Name: "Coursera"},
	{ID: "udemy", Name: "Udemy"},
	{ID: "edx", Name: "edX"},
	{ID: "khanacademy", Name: "Khan Academy"},
	{ID: "duolingo", Name: "Duolingo"},
	{ID: "autodesk", Name: "Autodesk"},
	{ID: "framer", Name: "Framer"},
	{ID: "clickup", Name: "ClickUp"},
	{ID: "linear", Name: "Linear"},
	{ID: "zapier", Name: "Zapier"},
	{ID: "teamviewer", Name: "TeamViewer"},
	{ID: "anydesk", Name: "AnyDesk"},
	{ID: "wetransfer", Name: "WeTransfer"},
	{ID: "upwork", Name: "Upwork"},
	{ID: "npmjs", Name: "npm"},
	{ID: "github", Name: "GitHub"},
	{ID: "gitlab", Name: "GitLab"},
	{ID: "cursor", Name: "Cursor"},
	{ID: "windsurf", Name: "Windsurf"},
	{ID: "jetbrains", Name: "JetBrains"},
	{ID: "docker", Name: "Docker Hub"},
	{ID: "hashicorp", Name: "HashiCorp"},
	{ID: "python", Name: "Python"},
	{ID: "golang", Name: "Go"},
	{ID: "rust", Name: "Rust"},
	{ID: "stackexchange", Name: "Stack Overflow"},
	{ID: "unity", Name: "Unity"},
	{ID: "anaconda", Name: "Anaconda"},
	{ID: "intel", Name: "Intel"},
	{ID: "amd", Name: "AMD"},
	{ID: "nvidia", Name: "NVIDIA"},
	{ID: "vercel", Name: "Vercel"},
	{ID: "netlify", Name: "Netlify"},
	{ID: "digitalocean", Name: "DigitalOcean"},
	{ID: "heroku", Name: "Heroku"},
	{ID: "codeberg", Name: "Codeberg"},
	{ID: "oracle", Name: "Oracle"},
	{ID: "mongodb", Name: "MongoDB"},
	{ID: "redis", Name: "Redis"},
	{ID: "sentry", Name: "Sentry"},
	{ID: "ngrok", Name: "ngrok"},
	{ID: "hetzner", Name: "Hetzner"},
	{ID: "qt", Name: "Qt"},
	{ID: "vmware", Name: "VMware"},
	{ID: "grafana", Name: "Grafana"},
	{ID: "arduino", Name: "Arduino"},
	{ID: "amazon", Name: "Amazon"},
	{ID: "ebay", Name: "eBay"},
	{ID: "etsy", Name: "Etsy"},
	{ID: "ikea", Name: "IKEA"},
	{ID: "nike", Name: "Nike"},
	{ID: "adidas", Name: "Adidas"},
	{ID: "hm", Name: "H&M"},
	{ID: "walmart", Name: "Walmart"},
	{ID: "shopify", Name: "Shopify"},
	{ID: "iherb", Name: "iHerb"},
	{ID: "bestbuy", Name: "Best Buy"},
	{ID: "booking", Name: "Booking"},
	{ID: "airbnb", Name: "Airbnb"},
	{ID: "expedia", Name: "Expedia"},
	{ID: "tripadvisor", Name: "Tripadvisor"},
	{ID: "skyscanner", Name: "Skyscanner"},
	{ID: "uber", Name: "Uber"},
	{ID: "paypal", Name: "PayPal"},
	{ID: "wise", Name: "Wise"},
	{ID: "revolut", Name: "Revolut"},
	{ID: "stripe", Name: "Stripe"},
	{ID: "payoneer", Name: "Payoneer"},
	{ID: "zone-ru", Name: ".ru .рф"},
	{ID: "zone-su", Name: ".su"},
	{ID: "geo-ru", Name: "Russian networks"},
	{ID: "okko", Name: "Okko"},
	{ID: "dzen", Name: "Dzen"},
	{ID: "2gis", Name: "2GIS"},
	{ID: "yandex", Name: "Yandex"},
	{ID: "vk", Name: "VK"},
	{ID: "ok", Name: "OK"},
	{ID: "mailru-group", Name: "Mail.ru"},
	{ID: "sberbank", Name: "Sber"},
	{ID: "tbank-ru", Name: "T-Bank"},
	{ID: "ozon", Name: "Ozon"},
	{ID: "wildberries", Name: "Wildberries"},
	{ID: "avito", Name: "Avito"},
	{ID: "kinopoisk", Name: "Kinopoisk"},
	{ID: "wink", Name: "Wink"},
	{ID: "rutube", Name: "Rutube"},
	{ID: "mts-ru", Name: "MTS"},
	{ID: "megafon", Name: "MegaFon"},
	{ID: "rostelecom", Name: "Rostelecom"},
	{ID: "t2-ru", Name: "T2"},
	{ID: "kaspersky", Name: "Kaspersky"},
	{ID: "headhunter", Name: "hh.ru"},
	{ID: "cdek", Name: "CDEK"},
	{ID: "gismeteo", Name: "Gismeteo"},
	{ID: "ru-more", Name: "More Russian services"},
}

var Bundles = []Bundle{
	{ID: "ai", Name: "AI", Members: []string{
		"openai", "anthropic", "gemini", "copilot", "github-copilot", "grok",
		"perplexity", "deepseek", "mistral", "poe", "huggingface", "groq",
		"manus", "cerebras", "character-ai", "midjourney", "suno", "udio",
		"elevenlabs", "runway", "pika", "leonardo", "ideogram", "deepl",
		"openrouter", "genspark", "recraft",
	}},
	{ID: "streaming", Name: "Streaming", Members: []string{
		"youtube", "twitch", "netflix", "spotify", "kick", "soundcloud",
		"apple-music", "apple-tvplus", "disney", "hbo", "primevideo", "hulu",
		"deezer", "tidal", "vimeo", "dailymotion", "plex", "bandcamp",
		"rumble", "dazn", "mubi", "crunchyroll", "lastfm",
	}},
	{ID: "social", Name: "Social", Members: []string{
		"meta", "x", "tiktok", "reddit", "linkedin", "pinterest",
		"snap", "tumblr", "bluesky", "quora", "medium", "patreon",
		"deviantart", "pixiv", "imgur", "flickr",
	}},
	{ID: "messengers", Name: "Messengers", Members: []string{
		"telegram", "discord", "whatsapp", "signal", "viber", "line",
		"teamspeak",
	}},
	{ID: "games", Name: "Games", Members: []string{
		"steam", "epicgames", "activision-blizzard", "ea", "riot", "roblox",
		"mojang", "xbox", "playstation", "nintendo", "ubisoft", "take-two",
		"gog", "wargaming", "gaijin", "escapefromtarkov", "faceit", "supercell",
		"hoyoverse", "pubg", "curseforge", "modrinth", "itchio", "humblebundle",
		"geforce-now", "chess", "bethesda",
	}},
	{ID: "work", Name: "Work", Members: []string{
		"notion", "slack", "zoom", "google-meet", "figma", "canva",
		"miro", "atlassian", "adobe", "grammarly", "dropbox", "mega",
		"evernote", "wix", "coursera", "udemy", "edx", "khanacademy",
		"duolingo", "autodesk", "framer", "clickup", "linear", "zapier",
		"teamviewer", "anydesk", "wetransfer", "upwork",
	}},
	{ID: "dev", Name: "Development", Members: []string{
		"npmjs", "github", "gitlab", "cursor", "windsurf", "jetbrains",
		"docker", "hashicorp", "python", "golang", "rust", "stackexchange",
		"unity", "anaconda", "intel", "amd", "nvidia", "vercel",
		"netlify", "digitalocean", "heroku", "codeberg", "oracle", "mongodb",
		"redis", "sentry", "ngrok", "hetzner", "qt", "vmware",
		"grafana", "arduino",
	}},
	{ID: "shopping", Name: "Shopping", Members: []string{
		"amazon", "ebay", "etsy", "ikea", "nike", "adidas",
		"hm", "walmart", "shopify", "iherb", "bestbuy",
	}},
	{ID: "travel", Name: "Travel", Members: []string{
		"booking", "airbnb", "expedia", "tripadvisor", "skyscanner", "uber",
	}},
	{ID: "finance", Name: "Finance", Members: []string{
		"paypal", "wise", "revolut", "stripe", "payoneer",
	}},
	{ID: "ru", Name: "Russia", Members: []string{
		"zone-ru", "zone-su", "geo-ru", "okko", "dzen", "2gis",
		"yandex", "vk", "ok", "mailru-group", "sberbank", "tbank-ru",
		"ozon", "wildberries", "avito", "kinopoisk", "wink", "rutube",
		"mts-ru", "megafon", "rostelecom", "t2-ru", "kaspersky", "headhunter",
		"cdek", "gismeteo", "ru-more",
	}},
}
